### ISSUE TITLE
Bearbeitung übergeordnete Texte

### ISSUE THREAD

**Issue by anneheichler** [zfhui/Aufbau-Ost-Berlin#6]
Fei, kannst du es eigentlich so einrichten, dass Lina und ich die übergeordneten Texte auch bearbeiten können oder ist das sehr kompliziert?

**Comment by zfhui** [comment]
Wird etwas Arbeit brauchen, aber das steht schon auf meiner (mentalen) Todo-Liste. Aber jetzt haben wir ein Issue dafür! :+1:

**Comment by zfhui** [comment]
Ich habe Contentful eingeführt mit dem man die Übergeordneten Texte (z.B. Intro) bearbeiten kann. 

Ich werde nach und nach auch die anderen Inhalte zum Contentful holen, weil es mir viel Arbeit erspart einen CMS bereitzustellen. 

Für den Zugang meldet euch bitte bei mir!
